version: '2'
services:
  nginx:
    build:
      context: .
      dockerfile: containers/nginx/Dockerfile
    ports:
      - "80:80"
    expose:
      - "80"
    stdin_open: true
    tty: true
    volumes:
     - ./code:/code 
     - ../cgi-bin:/cgi-bin
    command: nginx
  php-fpm:
    build:
      context: .
      dockerfile: containers/php-fpm/Dockerfile
    expose:
      - "9000"
    volumes:
      - ./code:/code
      - ../cgi-bin:/cgi-bin
    stdin_open: true
    tty: true
    command: php-fpm

